config/routes.rb
SIVIC::Application.routes.draw do

  resources :sivic_fechamentos

  resources :sivic_atividadepessoas do
    member do
      get :altera_situacao   
    end
  end

  resources :sivic_situacaoatividades

  resources :sivic_periodicidadecons

  resources :sivic_atividades do
    member do
      get :deleta_atividade
    end
  end

  resources :sivic_planos

  resources :sivic_modulos

  resources :sivic_models

  resources :sivic_contcategories

  resources :sivic_userpermissaos

  resources :sivic_permissaos

  resources :sivic_contatos

  resources :sivic_inscricaos

  resources :sivic_ministeriodiscipulos do
      member do
        get :adicionaministerio
      end
  end


  resources :sivic_situacaodiscipulos do
    member do
      get :deletasituacao
    end
  end
  #get '/deletasituacao/:id', to: 'sivic_situacaodiscipulos#deleta_situacao', as: 'deletasituacao'
  #match '/deletasituacao/:id', to: 'sivic_situacaodiscipulos#deleta_situacao', via: 'patch'

  resources :sivic_notaalunos do
     member do
       get :licaonota
     end
      member do
       get :notaaluno
     end
   
  end

  resources :sivic_alunoaulas do
    member do
       get :aulafrequencia
    end
    member do
      get :frequencia
    end
  end

  resources :sivic_aulas

  resources :sivic_licaos

  resources :sivic_cursos

  resources :sivic_turmaalunos

  resources :sivic_turmamoduloprofessors do
    member do
      get :aula
     end
   end

  resources :sivic_lancamentos

  resources :sivic_categories

  resources :sivic_centrocustos
  resources :sivic_fornecedors
  resources :sivic_contabancos
  resources :sivic_bancos
  resources :sivic_moduloturmas
  resources :sivic_moduloescolas
  resources :sivic_turmas
  resources :sivic_professors
  resources :sivic_contcelulas
  resources :sivic_contdiscipulos
  resources :observacoesrelatorios
  resources :sivic_situacoesrelatorios
  resources :sivic_sitpartcelulas

  resources :sivic_discipulos do
    member do
      get :deleta_pessoa_discipulo
    end
     member do
      get :new1
    end
  end

  resources :sivic_movimentofinanceiros 
  resources :sivic_partevenrelacelulas
  resources :sivic_participantecelulas
  resources :sivic_relatorioscelulas
  resources :sivic_celulas
  resources :sivic_escolaridades
  resources :sivic_ministerios

  resources :sivic_pessoas do
    member do
      get :deleta_pessoa
    end
  end
  
  resources :sivic_eventos
  resources :sivic_tipo_eventos
  resources :sivic_redes
  resources :sivic_tipo_eventos
  resources :sivic_escolaridades
  resources :sivic_profissaos
  resources :sivic_enderecos
  
  resources :sivic_igrejas do 
    resources :sivic_enderecos
  end

  resources :sivic_estados do
    resources :sivic_cidades
  end

  resources :sivic_relatorioscelulas do
    resources :sivic_partevenrelacelulas
  end

  resources :sivic_parteventos do
    resources :sivic_movimentofinanceiros   
  end

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/planos', to: 'static_pages#plan', via: 'get'
  match '/report', to: 'static_pages#report', via: 'get'

  match '/participantesEventos', to: 'sivic_parteventos#participanteseventos', via: 'get'
  match '/participanteseventogeracao', to: 'sivic_parteventos#participanteseventogeracao', via: 'get'

  match '/relMembros', to: 'sivic_discipulos#relMembros', via: 'get'
  match '/relAniversariantes', to: 'sivic_discipulos#relAniversariantes', via: 'get'

  match '/jobCelulas', to: 'sivic_relatorioscelulas#jobCelulas', via: 'get'

  match '/lancarRelatorio', to: 'sivic_relatorioscelulas#lanca_relatorio', via: 'get'

  get '/relDiscipulos/:id', to: 'sivic_discipulos#relDiscipulos', as: 'relDiscipulos'
  get '/relGeracoes/:id', to: 'sivic_discipulos#relGeracoes', as: 'relGeracoes'

  get '/relCelulas/:id', to: 'sivic_discipulos#relCelulas', as: 'relCelulas'

  match '/relGeracoesIndex', to: 'sivic_discipulos#relGeracoesIndex', via: 'get'

  match '/relCelulasGeracao', to: 'sivic_discipulos#relCelulasGeracao', via: 'get'

  match '/relCelulasGeracao', to: 'sivic_relatorioscelulas#relCelulasGeracao', via: 'get'


  get '/relEspelhoCelula/:id', to: 'sivic_relatorioscelulas#relEspelhoCelula', as: 'relEspelhoCelula'
  get '/relFrequenciaCelula/:id/:datainicio/:datafim', to: 'sivic_relatorioscelulas#relatoriofrequenciaCelula', as: 'relFrequenciaCelula'
   
  match '/celulasIndex', to: 'sivic_relatorioscelulas#celulasIndex', via: 'get'

  match '/frequenciaCelula', to: 'sivic_relatorioscelulas#frequenciaCelula', via: 'get'


  get '/relparticipantesEventos/:id/:tipo', to: 'sivic_parteventos#relparticipantesEventos', as: 'relparticipantesEventos'
  get '/relparticipantesEventoGeracao/:id/:tipo', to: 'sivic_parteventos#relparticipantesEventoGeracao', as: 'relparticipantesEventoGeracao'


  match '/admin', to: 'static_pages#index', via: 'get'
  match '/listarCidade', to: 'sivic_cidades#get_cities', via: 'get'
  match '/criarPessoa', to: 'sivic_pessoas#create_pessoa', via: 'get'
  match '/listarPessoa', to: 'sivic_pessoas#busca_pessoa', via: 'get'
  match '/editarNome', to: 'sivic_pessoas#edita_nome', via: 'get'
  match '/trocarigreja', to: 'sivic_pessoas#troca_igreja', via: 'get'

  match '/buscacategoria', to: 'sivic_categories#busca_categoria', via: 'get'

  match '/enviacontato', to: 'sivic_contatos#envia_contato', via: 'get'

  match '/listarDiscipulos', to: 'sivic_discipulos#busca_discipulos', via: 'get'
  match '/listarCelulas', to: 'sivic_celulas#busca_celulas', via: 'get'

  match '/criarParticipantesRelatorios', to: 'sivic_partevenrelacelulas#create_participante', via: 'get'
  match '/listarParticipantesCelulas', to: 'sivic_participantecelulas#busca_participante', via: 'get'
  match '/criarParticipantesCelulas', to: 'sivic_participantecelulas#create_participante', via: 'get'
  match '/listarEvento', to: 'sivic_eventos#buscaEvento', via: 'get'
  match '/buscaDiagrama', to: 'sivic_discipulos#buscaDiagrama', via: 'get'
  match '/criarEndereco', to: 'sivic_enderecos#create_endereco', via: 'get'
  match '/criarObservacaorelatorio', to: 'observacoesrelatorios#create_observacao', via: 'get'
  match '/alteraSituacao', to: 'sivic_relatorioscelulas#altera_situacao', via: 'get'
  match '/bloqueaCelula', to: 'sivic_celulas#bloquea', via: 'get'
  match '/desbloqueaCelula', to: 'sivic_celulas#desbloquea', via: 'get'
  match '/buscaTurmaProfessor', to: 'sivic_turmamoduloprofessors#busca_modulo_professor', via: 'get'

  match '/criarTurmaModuloProfessor', to: 'sivic_turmamoduloprofessors#create_turma_modulo_professor', via: 'get'
  
  match '/inserePagamento', to: 'sivic_lancamentos#create_pagamento', via: 'get'
  match '/alteraPagamento', to: 'sivic_lancamentos#edita_pagamento', via: 'get'
  match '/busca_lancamento', to: 'sivic_lancamentos#busca_lancamento', via: 'get'
  match '/editaPagaRecebe', to: 'sivic_lancamentos#edita_pagaRecebe', via: 'get'
  match '/deletaLancamento', to: 'sivic_lancamentos#deleta_lancamento', via: 'get'
  match '/setaPeriodo', to: 'sivic_lancamentos#seta_periodo', via: 'get'
  match '/insereDizimo', to: 'sivic_lancamentos#create_dizimo', via: 'get'
  match '/busca_dizimo', to: 'sivic_lancamentos#busca_dizimo', via: 'get'
  match '/editaDizimo', to: 'sivic_lancamentos#edita_dizimo', via: 'get'

  match '/insereTransferencia', to: 'sivic_lancamentos#create_transferencia', via: 'get'
  match '/editaTransferencia', to: 'sivic_lancamentos#edita_transferencia', via: 'get'
  match '/deletaTransferencia', to: 'sivic_lancamentos#deleta_transferencia', via: 'get'
  match '/buscaTransferencia', to: 'sivic_lancamentos#busca_transferencia', via: 'get'


  match '/listarTurma', to: 'sivic_turmaalunos#busca_turmas', via: 'get'

  get '/contasapagar', to: 'sivic_lancamentos#contasapagar',as: 'contasapagar'
  get '/contasareceber', to: 'sivic_lancamentos#contasareceber',as: 'contasareceber'
  get '/extrato', to: 'sivic_lancamentos#extrato',as: 'extrato'
  get '/extratomensal', to: 'sivic_lancamentos#extrato_mensal',as: 'extrato_mensal'

  match '/criarLicao', to: 'sivic_licaos#create_licao', via: 'get'
  match '/buscaLicao', to: 'sivic_licaos#busca_licao', via: 'get'
  match '/criarAula', to: 'sivic_aulas#create_aula', via: 'get'
  match '/buscaAula', to: 'sivic_aulas#busca_aula', via: 'get'
  match '/buscaAlunoAula', to: 'sivic_alunoaulas#busca_aluno_aula', via: 'get'
  match '/marcaAusente', to: 'sivic_alunoaulas#marcar_ausente', via: 'get'
  match '/marcaPresenca', to: 'sivic_alunoaulas#marcar_presenca', via: 'get'
  match '/buscaNotaAluno', to: 'sivic_notaalunos#busca_nota_aluno', via: 'get'
  match '/usuarios', to: 'sivic_discipulos#usuarios', via: 'get'

  

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  #Rotas de filtragem
  get '/filtrarelatorios/:sivic_situacoesrelatorio_id/:nome_pessoa', to: 'sivic_relatorioscelulas#index', as: 'filtrarelatorios'
  get '/filtraprofessor/:sivic_professor_situacao_id', to: 'sivic_professors#index', as: 'filtraprofessor'
  get '/filtraturma/:sivic_turma_situacao_id', to: 'sivic_turmas#index', as: 'filtraturma'


   get '/pEventos/:id', to: 'sivic_parteventos#naoParticipou', as: 'pEventos'
   get '/encerraEvento/:id', to: 'sivic_eventos#encerrar', as: 'encerraEvento'

   get '/bloqueaProfessor:id', to: 'sivic_professors#bloquea', as: 'bloqueaProfessor'
   get '/desbloqueaProfessor:id', to: 'sivic_professors#desbloquea', as: 'desbloqueaProfessor'

   get '/bloqueaTurmaaluno/:id', to: 'sivic_turmaalunos#bloquea', as: 'bloqueaTurmaaluno'
   get '/desbloqueaTurmaaluno/:id', to: 'sivic_turmaalunos#desbloquea', as: 'desbloqueaTurmaaluno'

   get '/bloqueaTurma/:id', to: 'sivic_turmas#bloquea', as: 'bloqueaTurma'
   get '/desbloqueaTurma/:id', to: 'sivic_turmas#desbloquea', as: 'desbloqueaTurma'

app/models/sivic_centrocusto.rb
class SivicCentrocusto < ActiveRecord::Base
  belongs_to :user
  belongs_to :sivic_igreja
end

app/controllers/sivic_centrocustos_controller.rb
class SivicCentrocustosController < ApplicationController
  before_action :set_sivic_centrocusto, only: [:show, :edit, :update, :destroy]

  # GET /sivic_centrocustos
  # GET /sivic_centrocustos.json
  def index
    @sivic_centrocustos = SivicCentrocusto.where(sivic_igreja_id: current_user.sivic_pessoa.sivic_igreja_id)
  end

  # GET /sivic_centrocustos/1
  # GET /sivic_centrocustos/1.json
  def show
  end

  # GET /sivic_centrocustos/new
  def new
    @sivic_centrocusto = SivicCentrocusto.new
  end

  # GET /sivic_centrocustos/1/edit
  def edit
  end

  # POST /sivic_centrocustos
  # POST /sivic_centrocustos.json
  def create
    @sivic_centrocusto = SivicCentrocusto.new(sivic_centrocusto_params)

    respond_to do |format|
      if @sivic_centrocusto.save
        format.html { redirect_to @sivic_centrocusto, notice: 'Registro inserido com sucesso.' }
        format.json { render action: 'show', status: :created, location: @sivic_centrocusto }
      else
        format.html { render action: 'new' }
        format.json { render json: @sivic_centrocusto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sivic_centrocustos/1
  # PATCH/PUT /sivic_centrocustos/1.json
  def update
    respond_to do |format|
      if @sivic_centrocusto.update(sivic_centrocusto_params)
        format.html { redirect_to @sivic_centrocusto, notice: 'Registro alterado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sivic_centrocusto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sivic_centrocustos/1
  # DELETE /sivic_centrocustos/1.json
  def destroy
    @sivic_centrocusto.destroy
    respond_to do |format|
      format.html { redirect_to sivic_centrocustos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sivic_centrocusto
      @sivic_centrocusto = SivicCentrocusto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sivic_centrocusto_params
      params.require(:sivic_centrocusto).permit(:nome_centrocusto, :desc_centrocusto, :user_id, :sivic_igreja_id)
    end
end

app/helpers/sivic_centrocustos_helper.rb
module SivicCentrocustosHelper
end

app/views/sivic_centrocustos/_form.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= 'Cadastro de Centro de Custo'%></h3>
  </div>
  <div class="panel-footer">

  <%= form_for(@sivic_centrocusto) do |f| %>
    <% if @sivic_centrocusto.errors.any? %>
  
      <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>

        <% if @sivic_centrocusto.errors.any? %>
  
            <% @sivic_centrocusto.errors.full_messages.each do |msg| %>

          <%= msg %></br>
        <% end %>
      <% end %>
      </div>
    <% end %>

  <div class="row">
      <div class="col-xs-3">
      </div>

      <div class="col-xs-6">
        <%= f.label :nome  %><br>
        <%= f.text_field :nome_centrocusto, :class =>  'form-control' %>
      </div>
  </div>
</br>
<div class="row">
      <div class="col-xs-3">
      </div>
      
      <div class="col-xs-6">      
          <%= f.label :Descrição %><br>
          <%= f.text_area :desc_centrocusto, :class =>  'form-control' %>
      </div>

</div>
</br>
   
       <!--Capturando igreja do usuaário logado -->
    <%= f.hidden_field :sivic_igreja_id, :value => current_user.sivic_pessoa.sivic_igreja_id %>
    <!--Capturando Usuário logado --> 
    <%= f.hidden_field :user_id, :value => current_user.id%> 

    </div>
</div>

<div class="btn-group">
  <button type="submit" class="btn btn-default btn">
    <span class="glyphicon glyphicon-floppy-disk"></span> Salvar
  </button>

  <%= yield(:iconexibir) %>


  <%= link_to sivic_centrocustos_path, :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
  <% end %>
</div>

<% end %>

app/views/sivic_centrocustos/edit.html.erb
<%= render 'form' %>

app/views/sivic_centrocustos/index.html.erb
<% content_for :titlePage do %>
  Lista de centro de Custo
<% end %>

<%=render '/layouts/panel' %>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>    
    </tr>
  </thead>

  <tbody>
    <% @sivic_centrocustos.each do |sivic_centrocusto| %>
      <tr>
        <td><%= sivic_centrocusto.nome_centrocusto %></td>
         <td align='right'>   
          <%= link_to sivic_centrocusto, :class => "btn btn-default btn-sm", :rel=>"tooltip", :title=>"Exibir" do %>
            <span class="glyphicon glyphicon-list-alt"></span>
          <% end %>             
          <%= link_to edit_sivic_centrocusto_path(sivic_centrocusto), :class => "btn btn-default btn-sm", :rel=>"tooltip", :title=>"Editar" do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>

           <a class="btn btn-default btn-sm" title="" rel="tooltip" href="/sivic_centrocustos/<%=sivic_centrocusto.id%>"  data-method="delete" data-confirm="Deseja   excluir o registro?" data-original-title="Excluir">
                <span class="glyphicon glyphicon-trash" rel="tooltip"></span>
            </a>       
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div></div>
<div class="btn-group">
  <%= link_to new_sivic_centrocusto_path, :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-file"></span> Novo
  <% end %>
</div>




<script>


$(function(){
  $("a[rel='tooltip']").tooltip();
})

</script>

app/views/sivic_centrocustos/new.html.erb
<%= render 'form' %>

app/views/sivic_centrocustos/show.html.erb
<%if notice %>
  <div class="alert alert-success alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
     <%= notice %>
</div>
<%end%>

<% content_for :titlePage do %>
  Exibir Cetro de custo
<% end %>

<%= render 'layouts/panel' %>

<p>
  <strong>Nome:</strong>
  <%= @sivic_centrocusto.nome_centrocusto %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @sivic_centrocusto.desc_centrocusto %>
</p>


</div></div>
<div class="btn-group">

  <%= link_to edit_sivic_centrocusto_path(@sivic_centrocusto), :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-pencil"></span> Editar
  <% end %>


  <%= link_to sivic_centrocustos_path, :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
  <% end %>

</div>