config/routes.rb
SIVIC::Application.routes.draw do

  resources :sivic_fechamentos

  resources :sivic_atividadepessoas do
    member do
      get :altera_situacao   
    end
  end

  resources :sivic_situacaoatividades

  resources :sivic_periodicidadecons

  resources :sivic_atividades do
    member do
      get :deleta_atividade
    end
  end

  resources :sivic_planos

  resources :sivic_modulos

  resources :sivic_models

  resources :sivic_contcategories

  resources :sivic_userpermissaos

  resources :sivic_permissaos

  resources :sivic_contatos

  resources :sivic_inscricaos

  resources :sivic_ministeriodiscipulos do
      member do
        get :adicionaministerio
      end
  end


  resources :sivic_situacaodiscipulos do
    member do
      get :deletasituacao
    end
  end
  #get '/deletasituacao/:id', to: 'sivic_situacaodiscipulos#deleta_situacao', as: 'deletasituacao'
  #match '/deletasituacao/:id', to: 'sivic_situacaodiscipulos#deleta_situacao', via: 'patch'

  resources :sivic_notaalunos do
     member do
       get :licaonota
     end
      member do
       get :notaaluno
     end
   
  end

  resources :sivic_alunoaulas do
    member do
       get :aulafrequencia
    end
    member do
      get :frequencia
    end
  end

  resources :sivic_aulas

  resources :sivic_licaos

  resources :sivic_cursos

  resources :sivic_turmaalunos

  resources :sivic_turmamoduloprofessors do
    member do
      get :aula
     end
   end

  resources :sivic_lancamentos

  resources :sivic_categories

  resources :sivic_centrocustos
  resources :sivic_fornecedors
  resources :sivic_contabancos
  resources :sivic_bancos
  resources :sivic_moduloturmas
  resources :sivic_moduloescolas
  resources :sivic_turmas
  resources :sivic_professors
  resources :sivic_contcelulas
  resources :sivic_contdiscipulos
  resources :observacoesrelatorios
  resources :sivic_situacoesrelatorios
  resources :sivic_sitpartcelulas

  resources :sivic_discipulos do
    member do
      get :deleta_pessoa_discipulo
    end
     member do
      get :new1
    end
  end

  resources :sivic_movimentofinanceiros 
  resources :sivic_partevenrelacelulas
  resources :sivic_participantecelulas
  resources :sivic_relatorioscelulas
  resources :sivic_celulas
  resources :sivic_escolaridades
  resources :sivic_ministerios

  resources :sivic_pessoas do
    member do
      get :deleta_pessoa
    end
  end
  
  resources :sivic_eventos
  resources :sivic_tipo_eventos
  resources :sivic_redes
  resources :sivic_tipo_eventos
  resources :sivic_escolaridades
  resources :sivic_profissaos
  resources :sivic_enderecos
  
  resources :sivic_igrejas do 
    resources :sivic_enderecos
  end

  resources :sivic_estados do
    resources :sivic_cidades
  end

  resources :sivic_relatorioscelulas do
    resources :sivic_partevenrelacelulas
  end

  resources :sivic_parteventos do
    resources :sivic_movimentofinanceiros   
  end

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/planos', to: 'static_pages#plan', via: 'get'
  match '/report', to: 'static_pages#report', via: 'get'

  match '/participantesEventos', to: 'sivic_parteventos#participanteseventos', via: 'get'
  match '/participanteseventogeracao', to: 'sivic_parteventos#participanteseventogeracao', via: 'get'

  match '/relMembros', to: 'sivic_discipulos#relMembros', via: 'get'
  match '/relAniversariantes', to: 'sivic_discipulos#relAniversariantes', via: 'get'

  match '/jobCelulas', to: 'sivic_relatorioscelulas#jobCelulas', via: 'get'

  match '/lancarRelatorio', to: 'sivic_relatorioscelulas#lanca_relatorio', via: 'get'

  get '/relDiscipulos/:id', to: 'sivic_discipulos#relDiscipulos', as: 'relDiscipulos'
  get '/relGeracoes/:id', to: 'sivic_discipulos#relGeracoes', as: 'relGeracoes'

  get '/relCelulas/:id', to: 'sivic_discipulos#relCelulas', as: 'relCelulas'

  match '/relGeracoesIndex', to: 'sivic_discipulos#relGeracoesIndex', via: 'get'

  match '/relCelulasGeracao', to: 'sivic_discipulos#relCelulasGeracao', via: 'get'

  match '/relCelulasGeracao', to: 'sivic_relatorioscelulas#relCelulasGeracao', via: 'get'


  get '/relEspelhoCelula/:id', to: 'sivic_relatorioscelulas#relEspelhoCelula', as: 'relEspelhoCelula'
  get '/relFrequenciaCelula/:id/:datainicio/:datafim', to: 'sivic_relatorioscelulas#relatoriofrequenciaCelula', as: 'relFrequenciaCelula'
   
  match '/celulasIndex', to: 'sivic_relatorioscelulas#celulasIndex', via: 'get'

  match '/frequenciaCelula', to: 'sivic_relatorioscelulas#frequenciaCelula', via: 'get'


  get '/relparticipantesEventos/:id/:tipo', to: 'sivic_parteventos#relparticipantesEventos', as: 'relparticipantesEventos'
  get '/relparticipantesEventoGeracao/:id/:tipo', to: 'sivic_parteventos#relparticipantesEventoGeracao', as: 'relparticipantesEventoGeracao'


  match '/admin', to: 'static_pages#index', via: 'get'
  match '/listarCidade', to: 'sivic_cidades#get_cities', via: 'get'
  match '/criarPessoa', to: 'sivic_pessoas#create_pessoa', via: 'get'
  match '/listarPessoa', to: 'sivic_pessoas#busca_pessoa', via: 'get'
  match '/editarNome', to: 'sivic_pessoas#edita_nome', via: 'get'
  match '/trocarigreja', to: 'sivic_pessoas#troca_igreja', via: 'get'

  match '/buscacategoria', to: 'sivic_categories#busca_categoria', via: 'get'

  match '/enviacontato', to: 'sivic_contatos#envia_contato', via: 'get'

  match '/listarDiscipulos', to: 'sivic_discipulos#busca_discipulos', via: 'get'
  match '/listarCelulas', to: 'sivic_celulas#busca_celulas', via: 'get'

  match '/criarParticipantesRelatorios', to: 'sivic_partevenrelacelulas#create_participante', via: 'get'
  match '/listarParticipantesCelulas', to: 'sivic_participantecelulas#busca_participante', via: 'get'
  match '/criarParticipantesCelulas', to: 'sivic_participantecelulas#create_participante', via: 'get'
  match '/listarEvento', to: 'sivic_eventos#buscaEvento', via: 'get'
  match '/buscaDiagrama', to: 'sivic_discipulos#buscaDiagrama', via: 'get'
  match '/criarEndereco', to: 'sivic_enderecos#create_endereco', via: 'get'
  match '/criarObservacaorelatorio', to: 'observacoesrelatorios#create_observacao', via: 'get'
  match '/alteraSituacao', to: 'sivic_relatorioscelulas#altera_situacao', via: 'get'
  match '/bloqueaCelula', to: 'sivic_celulas#bloquea', via: 'get'
  match '/desbloqueaCelula', to: 'sivic_celulas#desbloquea', via: 'get'
  match '/buscaTurmaProfessor', to: 'sivic_turmamoduloprofessors#busca_modulo_professor', via: 'get'

  match '/criarTurmaModuloProfessor', to: 'sivic_turmamoduloprofessors#create_turma_modulo_professor', via: 'get'
  
  match '/inserePagamento', to: 'sivic_lancamentos#create_pagamento', via: 'get'
  match '/alteraPagamento', to: 'sivic_lancamentos#edita_pagamento', via: 'get'
  match '/busca_lancamento', to: 'sivic_lancamentos#busca_lancamento', via: 'get'
  match '/editaPagaRecebe', to: 'sivic_lancamentos#edita_pagaRecebe', via: 'get'
  match '/deletaLancamento', to: 'sivic_lancamentos#deleta_lancamento', via: 'get'
  match '/setaPeriodo', to: 'sivic_lancamentos#seta_periodo', via: 'get'
  match '/insereDizimo', to: 'sivic_lancamentos#create_dizimo', via: 'get'
  match '/busca_dizimo', to: 'sivic_lancamentos#busca_dizimo', via: 'get'
  match '/editaDizimo', to: 'sivic_lancamentos#edita_dizimo', via: 'get'

  match '/insereTransferencia', to: 'sivic_lancamentos#create_transferencia', via: 'get'
  match '/editaTransferencia', to: 'sivic_lancamentos#edita_transferencia', via: 'get'
  match '/deletaTransferencia', to: 'sivic_lancamentos#deleta_transferencia', via: 'get'
  match '/buscaTransferencia', to: 'sivic_lancamentos#busca_transferencia', via: 'get'


  match '/listarTurma', to: 'sivic_turmaalunos#busca_turmas', via: 'get'

  get '/contasapagar', to: 'sivic_lancamentos#contasapagar',as: 'contasapagar'
  get '/contasareceber', to: 'sivic_lancamentos#contasareceber',as: 'contasareceber'
  get '/extrato', to: 'sivic_lancamentos#extrato',as: 'extrato'
  get '/extratomensal', to: 'sivic_lancamentos#extrato_mensal',as: 'extrato_mensal'

  match '/criarLicao', to: 'sivic_licaos#create_licao', via: 'get'
  match '/buscaLicao', to: 'sivic_licaos#busca_licao', via: 'get'
  match '/criarAula', to: 'sivic_aulas#create_aula', via: 'get'
  match '/buscaAula', to: 'sivic_aulas#busca_aula', via: 'get'
  match '/buscaAlunoAula', to: 'sivic_alunoaulas#busca_aluno_aula', via: 'get'
  match '/marcaAusente', to: 'sivic_alunoaulas#marcar_ausente', via: 'get'
  match '/marcaPresenca', to: 'sivic_alunoaulas#marcar_presenca', via: 'get'
  match '/buscaNotaAluno', to: 'sivic_notaalunos#busca_nota_aluno', via: 'get'
  match '/usuarios', to: 'sivic_discipulos#usuarios', via: 'get'

  

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  #Rotas de filtragem
  get '/filtrarelatorios/:sivic_situacoesrelatorio_id/:nome_pessoa', to: 'sivic_relatorioscelulas#index', as: 'filtrarelatorios'
  get '/filtraprofessor/:sivic_professor_situacao_id', to: 'sivic_professors#index', as: 'filtraprofessor'
  get '/filtraturma/:sivic_turma_situacao_id', to: 'sivic_turmas#index', as: 'filtraturma'


   get '/pEventos/:id', to: 'sivic_parteventos#naoParticipou', as: 'pEventos'
   get '/encerraEvento/:id', to: 'sivic_eventos#encerrar', as: 'encerraEvento'

   get '/bloqueaProfessor:id', to: 'sivic_professors#bloquea', as: 'bloqueaProfessor'
   get '/desbloqueaProfessor:id', to: 'sivic_professors#desbloquea', as: 'desbloqueaProfessor'

   get '/bloqueaTurmaaluno/:id', to: 'sivic_turmaalunos#bloquea', as: 'bloqueaTurmaaluno'
   get '/desbloqueaTurmaaluno/:id', to: 'sivic_turmaalunos#desbloquea', as: 'desbloqueaTurmaaluno'

   get '/bloqueaTurma/:id', to: 'sivic_turmas#bloquea', as: 'bloqueaTurma'
   get '/desbloqueaTurma/:id', to: 'sivic_turmas#desbloquea', as: 'desbloqueaTurma'

app/models/sivic_discipulo.rb
class SivicDiscipulo < ActiveRecord::Base

  # - RELACIONAMENTOS
  belongs_to :sivic_cidade
  belongs_to :sivic_pessoa
  belongs_to :sivic_endereco
  belongs_to :sivic_profissao
  belongs_to :sivic_escolaridade
  belongs_to :sivic_rede
  belongs_to :sivic_celula
  belongs_to :UsuarioInclusao, :class_name => "User", :foreign_key => "NUMG_UsuarioInclusao"	
  belongs_to :UsuarioBloqueio, :class_name => "User", :foreign_key => "NUMG_UsuarioBloqueio"
  belongs_to :ProfissaoConjuge, :class_name => "SivicProfissao", :foreign_key => "NUMG_ProfissaoConjuge"
  belongs_to :redeConversao, :class_name => "SivicRede", :foreign_key => "rede_conversao"

  # - STRONG ATRIBUTES
  accepts_nested_attributes_for :sivic_pessoa, allow_destroy: true
  accepts_nested_attributes_for :sivic_endereco, allow_destroy: true

  # - Domínio
  SEXO = %w[FEMININO MASCULINO]
  ESTADOCIVIL = %w[SOLTEIRO CASADO UNIAO_ESTAVEL OUTROS]
  DIAS = %w[SEGUNDA-FEIRA TERCA-FEIRA QUARTA-FEIRA QUINTA-FEIRA SEXTA-FEIRA SABADO DOMINGO]

  # - Validações
  #validates :NUMR_CPF, :cpf => { :message => ' - Digite um CPF valido' }
  #validates :sivic_profissao_id, :presence => { :message => ' - Escolha uma profissao' }
  #validates :sivic_pessoa_id, presence: true
  #validates :NUMR_CPF, uniqueness: true, uniqueness: {:message => 'ja esta sendo utlizado.'}
  #validates :sivic_endereco_id, :presence => { :message => 'Informe um endereco.' }
  #validates :sivic_escolaridade_id, :presence => { :message => ' - Informe a escolaridade' }
  #validates :sivic_rede_id, :presence => { :message => ' - Informe uma rede.' }
  #validates :data_nascimento, :presence => { :message => ' - Informe a data de nascimento' }
  #validates :NUMR_RG, :presence => { :message => ' - Informe o RG' }
  #validates :NUMR_RG, uniqueness: true, uniqueness: {message: ' - RG ja esta sendo utlizado'}


  before_destroy :capitura_pessoa
  after_destroy  :deleta_pessoa

  before_validation :retiraMascara

  @@codigo 
  @@pessoa 

  def self.find_by_name_or_all(query,sivic_igreja_id)
    
    if query
      query = query.downcase
       SivicPessoa.where('lower(nome_pessoa) like ? and sivic_igreja_id = ? and data_exclusao is null', "%#{query}%", sivic_igreja_id).order('NOME_pessoa')   
     # self.joins('LEFT JOIN sivic_pessoas sp on sivic_pessoa_id = sp.id').where('lower(sp.NOME_pessoa) like ? and sp.sivic_igreja_id = ? and sp.data_exclusao is null', "%#{query}%", sivic_igreja_id).order('NOME_pessoa')
    else
      SivicPessoa.where('sivic_igreja_id = ? and user_exclusao is null',sivic_igreja_id).order('NOME_pessoa')
     # self.joins('LEFT JOIN sivic_pessoas sp on sivic_pessoa_id = sp.id').where('sp.sivic_igreja_id = ? and sp.user_exclusao is null',sivic_igreja_id).order('NOME_pessoa')
    end    
  end

 def self.find_disc_by_name_or_all(query,sivic_igreja_id)
    
    if query
      query = query.downcase
     
      self.joins('LEFT JOIN sivic_pessoas sp on sivic_pessoa_id = sp.id').where('lower(sp.NOME_pessoa) like ? and sp.sivic_igreja_id = ? and sp.data_exclusao is null', "%#{query}%", sivic_igreja_id).order('NOME_pessoa')
    else
     
       self.joins('LEFT JOIN sivic_pessoas sp on sivic_pessoa_id = sp.id').where('sp.sivic_igreja_id = ? and sp.user_exclusao is null',sivic_igreja_id).order('NOME_pessoa')
    end    
  end


  def self.find_by_rel(query,sivic_igreja_id)    
    if query
      query = query.downcase
      self.joins('INNER JOIN sivic_pessoas sp on sivic_pessoa_id = sp.id').where('lower(sp.NOME_pessoa) like ? and sp.sivic_igreja_id = ?', "%#{query}%", sivic_igreja_id).order('NOME_pessoa')
    end    
  end  

  private

  def retiraMascara
      self.NUMR_CPF.gsub!(/[^0-9]/, '')
  end

  def deleta_pessoa
       @@pessoa.destroy  
  end

  def capitura_pessoa
       @@pessoa  = SivicPessoa.find(self.sivic_pessoa_id)      
  end
  
  
end

app/helpers/sivic_discipulos_helper.rb
module SivicDiscipulosHelper

	def BuscaPessoas(id)

	sivic_dados = SivicDiscipulo.joins('INNER JOIN sivic_pessoas sp on sivic_pessoa_id = sp.id where sp.father_id = ' + id.to_s)

		if sivic_dados

			html = '<ul>'

			sivic_dados.each do |sivic_pessoas|

			html += '<li>'
			
			html += '<a href="#">' + sivic_pessoas.sivic_pessoa.nome_pessoa + '</a>'

			html +=BuscaPessoas(sivic_pessoas.sivic_pessoa.id)

			html += '</li>'

			end

			html += '</ul>'
		end
			
		html = html.gsub('<ul></ul>', '')

		html.html_safe

	end

end

app/views/sivic_discipulos/edit.html.erb
<% content_for :iconexibir do %>
  <%= link_to @sivic_discipulo, :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-list-alt"></span> Exibir
  <% end %>  
<% end %>

<% content_for :editar do %>
<%='true'%>
<% end %>


<%if current_user.sivic_pessoa.sivic_igreja.flag_tradicional%>
	<%= render 'formTradicional' %>
<%else%>
	<%= render 'form' %>
<%end%>


app/views/sivic_discipulos/index.html.erb
<% content_for :titlePage do %>
  Listar Discípulos
<% end %>

<div id = "alert_placeholder_discipulo"></div>

<%=render '/layouts/panel' %>


<%= form_tag nil, method: 'GET' do %>
  <label >Nome</label><br>
  <div class="row">
    <div class="col-lg-12">
      <div class="input-group">
        <input id="q" name="q" type="text" class="form-control" placeholder="Nome">
        <span class="input-group-btn">
          <button class="btn btn-success" type="submit" >Buscar</button>
        </span>
      </div><!-- /input-group -->
    </div><!-- /.col-lg-6 -->
  </div><!-- /.row -->
  <br />  
<% end %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><strong class='titleTable'>Nome</strong></th>
        <th><strong class='titleTable'>Data de Nascimento</strong></th>
        <th><strong class='titleTable'>CPF</strong></th>
        <th><strong class='titleTable'>Data batismo</strong></th>
        <th></th>

      </tr>
    </thead>

    <tbody>
      <% @sivic_discipulos.each do |sivic_pessoa| %>
        <tr>
          <td><%= sivic_pessoa.nome_pessoa %></td>
          <% if sivic_pessoa.sivic_discipulo %></td>
            <td><%= sivic_pessoa.sivic_discipulo.data_nascimento.blank? ? '' : sivic_pessoa.sivic_discipulo.data_nascimento.strftime("%d/%m/%Y")  %></td>
            <td><%= sivic_pessoa.sivic_discipulo.NUMR_CPF %></td>
            <td><%= sivic_pessoa.sivic_discipulo.data_batismo.blank? ? '' : sivic_pessoa.sivic_discipulo.data_batismo.strftime("%d/%m/%Y")  %></td>
          <%else%>
            <td></td>
            <td></td>
            <td></td>
         <%end%>

        <%if sivic_pessoa.sivic_discipulo %>
          <td align='right'>
              <%= link_to sivic_pessoa.sivic_discipulo, :class => "btn btn-default btn-sm", :rel=>"tooltip", :title=>"Exibir" do %>
                <span class="glyphicon glyphicon-list-alt"></span>
              <% end %>             
              <%= link_to edit_sivic_discipulo_path(sivic_pessoa.sivic_discipulo.id), :class => "btn btn-default btn-sm", :rel=>"tooltip", :title=>"Editar" do %>
                <span class="glyphicon glyphicon-pencil"></span>
              <% end %>             
               <%= link_to deleta_pessoa_sivic_pessoa_path(sivic_pessoa), :confirm => 'Deseja excluir o discipulo?', :class => "btn btn-default btn-sm" , :rel=>"tooltip", :title=>"Excluir" do %>
                  <span class="glyphicon glyphicon-trash"></span> 
                <% end %>  
          </td> 
          <%else%>
          <td align='right'>

            <a class="btn btn-default btn-sm" title="" rel="tooltip" onclick="alert_boot('Não existe dados suficientes para exibir, favor evoluir cadastro clicando Editar.','warning','#alert_placeholder_discipulo');" data-original-title="Exibir">
                <span class="glyphicon glyphicon-list-alt" rel="tooltip"></span>
            </a> 

              <%= link_to new1_sivic_discipulo_path(sivic_pessoa), :class => "btn btn-default btn-sm", :rel=>"tooltip", :title=>"Editar" do %>
                <span class="glyphicon glyphicon-pencil"></span>
              <% end %>             
               <%= link_to deleta_pessoa_sivic_pessoa_path(sivic_pessoa), :confirm => 'Deseja excluir o discipulo?', :class => "btn btn-default btn-sm" , :rel=>"tooltip", :title=>"Excluir" do %>
                  <span class="glyphicon glyphicon-trash"></span> 
                <% end %>  
          </td> 
        <%end%>
                  
        </tr>
      <% end %>
    </tbody>
  </table>

<div class="apple_pagination">
<%= will_paginate @sivic_discipulo , :inner_window => 2%>
</div>

</div></div>
<div class="btn-group">
  <%= link_to new_sivic_discipulo_path, :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-file"></span> Novo
  <% end %>
</div>


<script>

$(function(){
  $("a[rel='tooltip']").tooltip();
})


function alert_boot(message,color,place) {

  $(place).html('<div class="alert alert-'+color+'" role="alert">'+message+'<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button> </div>')
}


</script>

app/views/sivic_discipulos/new.html.erb
<%if current_user.sivic_pessoa.sivic_igreja.flag_tradicional%>
	<%= render 'formTradicional' %>
<%else%>
	<%= render 'form' %>
<%end%>

app/views/sivic_discipulos/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for :titlePage do %>
  Exibir Discípulo
<% end %>

<%= render 'layouts/panel' %>

<p>
  <strong>Id:</strong>
  <%= @sivic_discipulo.NUMR_Codigo %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @sivic_discipulo.sivic_pessoa.nome_pessoa %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @sivic_discipulo.sivic_endereco.DESC_Rua %>
</p>

<p>
  <strong>Profissão:</strong>
  <%= @sivic_discipulo.sivic_profissao.profissao rescue nil %>
</p>

<p>
  <strong>Escolaridade:</strong>
  <%= @sivic_discipulo.sivic_escolaridade.NOME_escolaridade %>
</p>

<p>
  <strong>Rede:</strong>
  <%= @sivic_discipulo.sivic_rede.nome_rede rescue nil%>
</p>

<p>
  <strong>Célula:</strong>
  <%= @sivic_discipulo.sivic_celula.blank? ? '' : @sivic_discipulo.sivic_celula.NUMR_Dia%>
</p>

<p>
  <strong>Profissão do Conjuge:</strong>
  <%= @sivic_discipulo.ProfissaoConjuge.profissao rescue nil %>
</p>

<p>
  <strong>Usuário de Inclusão:</strong>
  <%= @sivic_discipulo.UsuarioInclusao.email %>
</p>


<p>
  <strong>Orientação Sexual:</strong>
  <%= @sivic_discipulo.desc_sexo %>
</p>

<p>
  <strong>Data de Nascimento:</strong>
  <%= @sivic_discipulo.data_nascimento %>
</p>

<p>
  <strong>Apelido:</strong>
  <%= @sivic_discipulo.DESC_Apelido %>
</p>

<p>
  <strong>Estado Civil:</strong>
  <%= @sivic_discipulo.desc_estadocivil %>
</p>

<p>
  <strong>Nome do Conjuge:</strong>
  <%= @sivic_discipulo.NOME_Conjuge %>
</p>

<p>
  <strong>Data da Decisão:</strong>
  <%= @sivic_discipulo.DATA_Decisao %>
</p>

<p>
  <strong>Quantidade de Filhos:</strong>
  <%= @sivic_discipulo.NUMR_QtdFilhos %>
</p>

<p>
  <strong>Discípulo:</strong>
  <%= @sivic_discipulo.flag_discipulo? ? "Sim" : "Não"%>
</p>

<p>
  <strong>Ocasião em que recebeu Cristo:</strong>
  <%if @sivic_discipulo.FLAG_OcasiaoRecebeuCristo == 0%>
    Célula
  <%elsif @sivic_discipulo.FLAG_OcasiaoRecebeuCristo == 1%>
    Celebração Evento
  <%elsif @sivic_discipulo.FLAG_OcasiaoRecebeuCristo == 2%>
    Evangelismo Pessoal
  <%elsif @sivic_discipulo.FLAG_OcasiaoRecebeuCristo == 3%>
    Culto Livre
  <%end%>
</p>

<p>
  <strong>Trabalhando:</strong>
  <%= @sivic_discipulo.FLAG_Trabalhando %>
</p>

<p>
  <strong>Momento Estudo Bíblico:</strong>
  <%= @sivic_discipulo.DESC_MomentoEstudoBiblico %>
</p>

<p>
  <strong>RG:</strong>
  <%= @sivic_discipulo.NUMR_RG %>
</p>

<p>
  <strong>Data de Expedição:</strong>
  <%= @sivic_discipulo.DATA_EmissaoRG %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @sivic_discipulo.NUMR_CPF %>
</p>

<p>
  <strong>Nome do Pai:</strong>
  <%= @sivic_discipulo.NOME_Pai %>
</p>

<p>
  <strong>Nome da Mãe:</strong>
  <%= @sivic_discipulo.NOME_Mae %>
</p>

<p>
  <strong>Data de Nascimento do Conjuge:</strong>
  <%= @sivic_discipulo.DATA_NascConjuge %>
</p>

<p>
  <strong>Data de Casamento:</strong>
  <%= @sivic_discipulo.DATA_Casamento %>
</p>

<p>
  <strong>Titulo Eleitoral:</strong>
  <%= @sivic_discipulo.NUMR_TituloEleitoral %>
</p>

<p>
  <strong>Data Batismo:</strong>
  <%= @sivic_discipulo.data_batismo %>
</p>

<p>
  <strong>Igreja de Batismo:</strong>
  <%= @sivic_discipulo.DESC_IgrejaBatismo %>
</p>

<p>
  <strong>Doador de Sangue:</strong>
  <%= @sivic_discipulo.FLAG_DoadorSangue? ? "Sim" : "Não"%>
</p>

<p>
  <strong>Doador de Órgao:</strong>
  <%= @sivic_discipulo.FLAG_DoadorOrgao? ? "Sim" : "Não" %>
</p>

</div>
</div>

<div class="btn-group">

  <%= link_to edit_sivic_discipulo_path(@sivic_discipulo), :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-pencil"></span> Editar
  <% end %>

  <%= link_to sivic_discipulo_path(format: 'pdf'), {:class => "btn btn-default", :target => '_blank'} do %>
    <span class="glyphicon glyphicon-print  "></span> PDF
  <% end %>

  <%= link_to sivic_discipulos_path, :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
  <% end %>

</div>


