config/routes.rb
SIVIC::Application.routes.draw do

  resources :sivic_fechamentos

  resources :sivic_atividadepessoas do
    member do
      get :altera_situacao   
    end
  end

  resources :sivic_situacaoatividades

  resources :sivic_periodicidadecons

  resources :sivic_atividades do
    member do
      get :deleta_atividade
    end
  end

  resources :sivic_planos

  resources :sivic_modulos

  resources :sivic_models

  resources :sivic_contcategories

  resources :sivic_userpermissaos

  resources :sivic_permissaos

  resources :sivic_contatos

  resources :sivic_inscricaos

  resources :sivic_ministeriodiscipulos do
      member do
        get :adicionaministerio
      end
  end


  resources :sivic_situacaodiscipulos do
    member do
      get :deletasituacao
    end
  end
  #get '/deletasituacao/:id', to: 'sivic_situacaodiscipulos#deleta_situacao', as: 'deletasituacao'
  #match '/deletasituacao/:id', to: 'sivic_situacaodiscipulos#deleta_situacao', via: 'patch'

  resources :sivic_notaalunos do
     member do
       get :licaonota
     end
      member do
       get :notaaluno
     end
   
  end

  resources :sivic_alunoaulas do
    member do
       get :aulafrequencia
    end
    member do
      get :frequencia
    end
  end

  resources :sivic_aulas

  resources :sivic_licaos

  resources :sivic_cursos

  resources :sivic_turmaalunos

  resources :sivic_turmamoduloprofessors do
    member do
      get :aula
     end
   end

  resources :sivic_lancamentos

  resources :sivic_categories

  resources :sivic_centrocustos
  resources :sivic_fornecedors
  resources :sivic_contabancos
  resources :sivic_bancos
  resources :sivic_moduloturmas
  resources :sivic_moduloescolas
  resources :sivic_turmas
  resources :sivic_professors
  resources :sivic_contcelulas
  resources :sivic_contdiscipulos
  resources :observacoesrelatorios
  resources :sivic_situacoesrelatorios
  resources :sivic_sitpartcelulas

  resources :sivic_discipulos do
    member do
      get :deleta_pessoa_discipulo
    end
     member do
      get :new1
    end
  end

  resources :sivic_movimentofinanceiros 
  resources :sivic_partevenrelacelulas
  resources :sivic_participantecelulas
  resources :sivic_relatorioscelulas
  resources :sivic_celulas
  resources :sivic_escolaridades
  resources :sivic_ministerios

  resources :sivic_pessoas do
    member do
      get :deleta_pessoa
    end
  end
  
  resources :sivic_eventos
  resources :sivic_tipo_eventos
  resources :sivic_redes
  resources :sivic_tipo_eventos
  resources :sivic_escolaridades
  resources :sivic_profissaos
  resources :sivic_enderecos
  
  resources :sivic_igrejas do 
    resources :sivic_enderecos
  end

  resources :sivic_estados do
    resources :sivic_cidades
  end

  resources :sivic_relatorioscelulas do
    resources :sivic_partevenrelacelulas
  end

  resources :sivic_parteventos do
    resources :sivic_movimentofinanceiros   
  end

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/planos', to: 'static_pages#plan', via: 'get'
  match '/report', to: 'static_pages#report', via: 'get'

  match '/participantesEventos', to: 'sivic_parteventos#participanteseventos', via: 'get'
  match '/participanteseventogeracao', to: 'sivic_parteventos#participanteseventogeracao', via: 'get'

  match '/relMembros', to: 'sivic_discipulos#relMembros', via: 'get'
  match '/relAniversariantes', to: 'sivic_discipulos#relAniversariantes', via: 'get'

  match '/jobCelulas', to: 'sivic_relatorioscelulas#jobCelulas', via: 'get'

  match '/lancarRelatorio', to: 'sivic_relatorioscelulas#lanca_relatorio', via: 'get'

  get '/relDiscipulos/:id', to: 'sivic_discipulos#relDiscipulos', as: 'relDiscipulos'
  get '/relGeracoes/:id', to: 'sivic_discipulos#relGeracoes', as: 'relGeracoes'

  get '/relCelulas/:id', to: 'sivic_discipulos#relCelulas', as: 'relCelulas'

  match '/relGeracoesIndex', to: 'sivic_discipulos#relGeracoesIndex', via: 'get'

  match '/relCelulasGeracao', to: 'sivic_discipulos#relCelulasGeracao', via: 'get'

  match '/relCelulasGeracao', to: 'sivic_relatorioscelulas#relCelulasGeracao', via: 'get'


  get '/relEspelhoCelula/:id', to: 'sivic_relatorioscelulas#relEspelhoCelula', as: 'relEspelhoCelula'
  get '/relFrequenciaCelula/:id/:datainicio/:datafim', to: 'sivic_relatorioscelulas#relatoriofrequenciaCelula', as: 'relFrequenciaCelula'
   
  match '/celulasIndex', to: 'sivic_relatorioscelulas#celulasIndex', via: 'get'

  match '/frequenciaCelula', to: 'sivic_relatorioscelulas#frequenciaCelula', via: 'get'


  get '/relparticipantesEventos/:id/:tipo', to: 'sivic_parteventos#relparticipantesEventos', as: 'relparticipantesEventos'
  get '/relparticipantesEventoGeracao/:id/:tipo', to: 'sivic_parteventos#relparticipantesEventoGeracao', as: 'relparticipantesEventoGeracao'


  match '/admin', to: 'static_pages#index', via: 'get'
  match '/listarCidade', to: 'sivic_cidades#get_cities', via: 'get'
  match '/criarPessoa', to: 'sivic_pessoas#create_pessoa', via: 'get'
  match '/listarPessoa', to: 'sivic_pessoas#busca_pessoa', via: 'get'
  match '/editarNome', to: 'sivic_pessoas#edita_nome', via: 'get'
  match '/trocarigreja', to: 'sivic_pessoas#troca_igreja', via: 'get'

  match '/buscacategoria', to: 'sivic_categories#busca_categoria', via: 'get'

  match '/enviacontato', to: 'sivic_contatos#envia_contato', via: 'get'

  match '/listarDiscipulos', to: 'sivic_discipulos#busca_discipulos', via: 'get'
  match '/listarCelulas', to: 'sivic_celulas#busca_celulas', via: 'get'

  match '/criarParticipantesRelatorios', to: 'sivic_partevenrelacelulas#create_participante', via: 'get'
  match '/listarParticipantesCelulas', to: 'sivic_participantecelulas#busca_participante', via: 'get'
  match '/criarParticipantesCelulas', to: 'sivic_participantecelulas#create_participante', via: 'get'
  match '/listarEvento', to: 'sivic_eventos#buscaEvento', via: 'get'
  match '/buscaDiagrama', to: 'sivic_discipulos#buscaDiagrama', via: 'get'
  match '/criarEndereco', to: 'sivic_enderecos#create_endereco', via: 'get'
  match '/criarObservacaorelatorio', to: 'observacoesrelatorios#create_observacao', via: 'get'
  match '/alteraSituacao', to: 'sivic_relatorioscelulas#altera_situacao', via: 'get'
  match '/bloqueaCelula', to: 'sivic_celulas#bloquea', via: 'get'
  match '/desbloqueaCelula', to: 'sivic_celulas#desbloquea', via: 'get'
  match '/buscaTurmaProfessor', to: 'sivic_turmamoduloprofessors#busca_modulo_professor', via: 'get'

  match '/criarTurmaModuloProfessor', to: 'sivic_turmamoduloprofessors#create_turma_modulo_professor', via: 'get'
  
  match '/inserePagamento', to: 'sivic_lancamentos#create_pagamento', via: 'get'
  match '/alteraPagamento', to: 'sivic_lancamentos#edita_pagamento', via: 'get'
  match '/busca_lancamento', to: 'sivic_lancamentos#busca_lancamento', via: 'get'
  match '/editaPagaRecebe', to: 'sivic_lancamentos#edita_pagaRecebe', via: 'get'
  match '/deletaLancamento', to: 'sivic_lancamentos#deleta_lancamento', via: 'get'
  match '/setaPeriodo', to: 'sivic_lancamentos#seta_periodo', via: 'get'
  match '/insereDizimo', to: 'sivic_lancamentos#create_dizimo', via: 'get'
  match '/busca_dizimo', to: 'sivic_lancamentos#busca_dizimo', via: 'get'
  match '/editaDizimo', to: 'sivic_lancamentos#edita_dizimo', via: 'get'

  match '/insereTransferencia', to: 'sivic_lancamentos#create_transferencia', via: 'get'
  match '/editaTransferencia', to: 'sivic_lancamentos#edita_transferencia', via: 'get'
  match '/deletaTransferencia', to: 'sivic_lancamentos#deleta_transferencia', via: 'get'
  match '/buscaTransferencia', to: 'sivic_lancamentos#busca_transferencia', via: 'get'


  match '/listarTurma', to: 'sivic_turmaalunos#busca_turmas', via: 'get'

  get '/contasapagar', to: 'sivic_lancamentos#contasapagar',as: 'contasapagar'
  get '/contasareceber', to: 'sivic_lancamentos#contasareceber',as: 'contasareceber'
  get '/extrato', to: 'sivic_lancamentos#extrato',as: 'extrato'
  get '/extratomensal', to: 'sivic_lancamentos#extrato_mensal',as: 'extrato_mensal'

  match '/criarLicao', to: 'sivic_licaos#create_licao', via: 'get'
  match '/buscaLicao', to: 'sivic_licaos#busca_licao', via: 'get'
  match '/criarAula', to: 'sivic_aulas#create_aula', via: 'get'
  match '/buscaAula', to: 'sivic_aulas#busca_aula', via: 'get'
  match '/buscaAlunoAula', to: 'sivic_alunoaulas#busca_aluno_aula', via: 'get'
  match '/marcaAusente', to: 'sivic_alunoaulas#marcar_ausente', via: 'get'
  match '/marcaPresenca', to: 'sivic_alunoaulas#marcar_presenca', via: 'get'
  match '/buscaNotaAluno', to: 'sivic_notaalunos#busca_nota_aluno', via: 'get'
  match '/usuarios', to: 'sivic_discipulos#usuarios', via: 'get'

  

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  #Rotas de filtragem
  get '/filtrarelatorios/:sivic_situacoesrelatorio_id/:nome_pessoa', to: 'sivic_relatorioscelulas#index', as: 'filtrarelatorios'
  get '/filtraprofessor/:sivic_professor_situacao_id', to: 'sivic_professors#index', as: 'filtraprofessor'
  get '/filtraturma/:sivic_turma_situacao_id', to: 'sivic_turmas#index', as: 'filtraturma'


   get '/pEventos/:id', to: 'sivic_parteventos#naoParticipou', as: 'pEventos'
   get '/encerraEvento/:id', to: 'sivic_eventos#encerrar', as: 'encerraEvento'

   get '/bloqueaProfessor:id', to: 'sivic_professors#bloquea', as: 'bloqueaProfessor'
   get '/desbloqueaProfessor:id', to: 'sivic_professors#desbloquea', as: 'desbloqueaProfessor'

   get '/bloqueaTurmaaluno/:id', to: 'sivic_turmaalunos#bloquea', as: 'bloqueaTurmaaluno'
   get '/desbloqueaTurmaaluno/:id', to: 'sivic_turmaalunos#desbloquea', as: 'desbloqueaTurmaaluno'

   get '/bloqueaTurma/:id', to: 'sivic_turmas#bloquea', as: 'bloqueaTurma'
   get '/desbloqueaTurma/:id', to: 'sivic_turmas#desbloquea', as: 'desbloqueaTurma'

app/models/sivic_model.rb
class SivicModel < ActiveRecord::Base
	has_many:sivic_permissaos 
	belongs_to:sivic_modulo
end

app/controllers/sivic_models_controller.rb
class SivicModelsController < ApplicationController
  before_action :set_sivic_model, only: [:show, :edit, :update, :destroy]

  # GET /sivic_models
  # GET /sivic_models.json
  def index
    @sivic_models = SivicModel.all
  end

  # GET /sivic_models/1
  # GET /sivic_models/1.json
  def show
  end

  # GET /sivic_models/new
  def new
    @sivic_model = SivicModel.new
  end

  # GET /sivic_models/1/edit
  def edit
  end

  # POST /sivic_models
  # POST /sivic_models.json
  def create
    @sivic_model = SivicModel.new(sivic_model_params)

    respond_to do |format|
      if @sivic_model.save
        format.html { redirect_to @sivic_model, notice: 'Sivic model was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sivic_model }
      else
        format.html { render action: 'new' }
        format.json { render json: @sivic_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sivic_models/1
  # PATCH/PUT /sivic_models/1.json
  def update
    respond_to do |format|
      if @sivic_model.update(sivic_model_params)
        format.html { redirect_to @sivic_model, notice: 'Sivic model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sivic_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sivic_models/1
  # DELETE /sivic_models/1.json
  def destroy
    @sivic_model.destroy
    respond_to do |format|
      format.html { redirect_to sivic_models_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sivic_model
      @sivic_model = SivicModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sivic_model_params
      params.require(:sivic_model).permit(:nome_model, :desc_model, :data_bloqueio, :sivic_modulo_id)
    end
end

app/helpers/sivic_models_helper.rb
module SivicModelsHelper
end

app/views/sivic_models/_form.html.erb
  <%= form_for(@sivic_model) do |f| %>
    <% if @sivic_model.errors.any? %>
     <div class="alert alert-danger alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <% if @sivic_model.errors.any? %>
  
            <% @sivic_model.errors.full_messages.each do |msg| %>

          <%= msg %></br>
        <% end %>
      <% end %>
      </div>
    <% end %>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= 'Cadastro de Models'%></h3>
  </div>
  <div class="panel-footer">

  <div class="row mar-bot40">
    <div class="col-lg-4" >
    </div>
    <div class="col-lg-4" >
      <%= f.label :Nome_Model %><br>
      <%= f.text_field :nome_model, :class => 'form-control' %>
    </div>
  </div>
  <div class="row mar-bot40">
    <div class="col-lg-4" >
    </div>  
    <div class="col-lg-4" >
      <%= f.label :Descrição%><br>
      <%= f.text_field :desc_model, :class => 'form-control' %>
    </div>
    <%#= f.label :data_bloqueio %>
    <%#= f.datetime_select :data_bloqueio %>
  </div>  
  <div class="row mar-bot40">
    <div class="col-lg-4" >
    </div>
  
      <div class="col-lg-4" >
        <%= f.label :Módulo%><br>
        <%= f.select :sivic_modulo_id, options_from_collection_for_select(SivicModulo.all, 'id', 'nome_modulo',@sivic_model.sivic_modulo_id), {}, {:class =>  'form-control'}%>
      </div>

    <%#= f.label :data_bloqueio %>
    <%#= f.datetime_select :data_bloqueio %>
  </div>
</div>
</div>

<div class="btn-group">

  <button type="submit" class="btn btn-default btn">
    <span class="glyphicon glyphicon-floppy-disk"></span> Salvar
  </button>

  <%= yield(:iconexibir) %>

  <%= link_to sivic_models_path, :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
  <% end %>

</div>
<% end %>

app/views/sivic_models/edit.html.erb
<%= render 'form' %>

app/views/sivic_models/index.html.erb
<% content_for :titlePage do %>
  Models
<% end %>

<%=render '/layouts/panel' %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Model</th>
      <th>Descrição</th>
      <th>Data bloqueio</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sivic_models.each do |sivic_model| %>
      <tr>
        <td><%= sivic_model.nome_model %></td>
        <td><%= sivic_model.desc_model %></td>
        <td><%= sivic_model.data_bloqueio %></td>
        <td align='right'>

            <%= link_to sivic_model, :class => "btn btn-default btn-sm", :rel=>"tooltip", :title=>"Exibir" do %>
              <span class="glyphicon glyphicon-list-alt"></span>
            <% end %>             
            <%= link_to edit_sivic_model_path(sivic_model), :class => "btn btn-default btn-sm", :rel=>"tooltip", :title=>"Editar"  do %>
              <span class="glyphicon glyphicon-pencil"></span> 
            <% end %>
             <a class="btn btn-default btn-sm" title="" rel="tooltip" href="/sivic_models/<%=sivic_model.id%>" data-method="delete" data-confirm="Deseja excluir o registro?" data-original-title="Excluir">
                <span class="glyphicon glyphicon-trash" rel="tooltip"></span>
            </a>  

        </td> 

      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div></div>

<div class="btn-group">
  <%= link_to new_sivic_model_path, :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-file"></span> Novo
  <% end %>
</div>

<script>
$(function(){
  $("a[rel='tooltip']").tooltip();
})
</script>

app/views/sivic_models/new.html.erb
<%= render 'form' %>

app/views/sivic_models/show.html.erb
<%if notice %>
  <div class="alert alert-success alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
     <%= notice %>
</div>
<%end%>

<% content_for :titlePage do %>
  Exibir Model
<% end %>

<%= render 'layouts/panel' %>

<p>
  <strong>Módulo:</strong>
  <%= @sivic_model.sivic_modulo.nome_modulo %>
</p>

<p>
  <strong>Nome do Model:</strong>
  <%= @sivic_model.nome_model %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @sivic_model.desc_model %>
</p>


<p>
  <strong>Data Bloqueio:</strong>
  <%= @sivic_model.data_bloqueio %>
</p>

</div></div>

<div class="btn-group">

  <%= link_to edit_sivic_model_path(@sivic_model), :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-pencil"></span> Editar
  <% end %>

  <%= link_to sivic_models_path, :class => "btn btn-default" do %>
    <span class="glyphicon glyphicon-arrow-left"></span> Voltar
  <% end %>

</div>